<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HPDA0017" ignored="0" name="Default test" tests="8" failures="1" timestamp="09 Jul 2018 09:29:55 GMT" time="0.083" errors="0">
  <testcase name="Test1_Able_To_Add_New_Entry_In_Collection" time="0.015" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test2_Duplicate_Entry_In_Collection" time="0.003" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test3_Get_Collection_Functionality" time="0.001" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.lang.String.concat(String.java:2027)
at question2.MyCollection.toString(MyCollection.java:145)
at testquestion2.Test_MyCollection.Test3_Get_Collection_Functionality(Test_MyCollection.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test3_Get_Collection_Functionality -->
  <testcase name="Test5_Remove_Functionality_If_Entry_Already_Present" time="0.002" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test6_Remove_Functionality_If_Collection_Is_Empty" time="0.001" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test7_Collection_Length_Functionality" time="0.004" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test8_Search_Functionality_If_Enrty_Exists" time="0.005" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test9_Search_Functionality_If_Enrty_Not_Exists" time="0.003" classname="testquestion2.Test_MyCollection"/>
</testsuite> <!-- Default test -->
